#Generates a plot to show the normalization effect, breaks glht for some reason
NormPlot <- function (T_Data, output, filename = "default") {
  originald <- getwd()
  dir.create(file.path(originald, output), showWarnings = FALSE)
  setwd(file.path(file.path(originald, output)))
  
  png(file = paste0(getwd(), "/", filename, ".png"), height = 1000,  width = 640)
  T_Data.melt <- melt(T_Data)
  T_Data.melt[T_Data.melt == -Inf] <- NA
  require(lattice)
  p1 <- histogram( ~ value | variable, T_Data.melt, ylab = "Abundance", xlab = "Sample")
  
  p2 <- bwplot(value ~ variable, T_Data.melt, scales=list(x=list(rot=45)), ylab = "Abundance", xlab = "Sample")
  
  grid.arrange(p1, p2, ncol = 1, nrow = 2)
  dev.off()
  setwd(originald)
}

#Generates a neat little heat map
QuickHeatMap <- function(mydata, myorder = NULL)
{
  require(ggplot2)
  data.m <- ddply(mydata, .(Peptide), transform, rescale = rescale(value))
  p <- ggplot(data.m, aes(Alias, Peptide)) + geom_tile(aes(fill = rescale),colour = "white")
  p + scale_fill_gradient(low = "white", high = "steelblue") +  theme(axis.text.x = element_text(angle = 45, hjust = 1))
}

#Generates a nicely formatted volcano plot
VolPlot <- function(inDatax, inDatay, output, maxy = NULL, filename = "default")
{
  inDatax <- as.numeric(inDatax)
  inDatay <- as.numeric(inDatay)
  originald <- getwd()
  dir.create(file.path(originald, output), showWarnings = FALSE)
  setwd(file.path(file.path(originald, output)))
  
  png(file = paste0(getwd(), "/", filename, ".png"), width = 640)
  if(is.null(maxy))
  {
    maxy = rev(range(inDatay[which(inDatay != 0)]))[2]  
  }
  maxx <- ceiling(max(abs(as.numeric(inDatax[which(inDatay != 0)]))))
  plot(inDatax, inDatay,  log = "y", ylim = c(1, maxy), xlim = c(-maxx, maxx), 
       xlab = "Log2(Fold-Change)", ylab = "p-value")
  grid(lwd = 3)
  abline(h = 0.05, col = "red")
  dev.off()
  setwd(originald)
}

#Exports the plots of confidence interval plots generated by plot.summary.glht
PlotTukeyResult <- function(tukeylist, output = "img")
{
  mydir <- getwd()
  dir.create(file.path(mydir, output), showWarnings = FALSE)
  setwd(file.path(mydir, output))
  for(i in names(tukeylist))
  {
    png(file = paste0(getwd(), "/", sub("|", "", i,fixed = TRUE),"_Tukey.png"), width = 640)
    par(mar =c(4, 20, 4, 4))
    plot(tukeylist[[i]])
    dev.off()
  }
  setwd(mydir)
}


#Generates a set of scatter plots for each comparison with correlation listed
# in upper right
PairPlot <- function(inData, output, filename = "default")
{
  originald <- getwd()
  dir.create(file.path(originald, output), showWarnings = FALSE)
  setwd(file.path(file.path(originald, output)))
  inData[inData == 0] <- NA
  inData <- log(inData,2)
  png(file = paste0(getwd(), "/", filename, ".png"), width = 640)
  pairs(inData, upper.panel = panel.cor, pch = ".")
  dev.off()
  setwd(originald)
}

#For use with the pairs function, provides the correlations
panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor, ...)
{
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  r <- abs(cor(x, y, use = "pairwise.complete.obs"))
  txt <- format(c(r, 0.123456789), digits = digits)[1]
  txt <- paste(prefix, txt, sep = "")
  if(missing(cex.cor)) cex.cor <- 0.8/strwidth(txt)
  text(0.5, 0.5, txt, cex = cex.cor * r)
}